import pyautogui
import time
x = 0
lista = 100
pyautogui.alert("o código vai começar")
pyautogui.PAUSE = 0.3

for x in range(3):
    time.sleep(1)
    pyautogui.moveTo(848, 143)
    pyautogui.click()
    pyautogui.write('EMPRESA')
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.write('XX.XXX.XXX/XXXX-XX')
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.write('cnpj')
    time.sleep(0.5)
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.write('5')
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.write('0')
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.write('0')
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.write('0')
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.write('1')
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.write('3')
    pyautogui.press('tab')
    pyautogui.moveTo(958, 661)
    # pyautogui.click()
    time.sleep(0.5)
    pyautogui.moveTo(445, 85)
    # pyautogui.click()
    time.sleep(1)
    if pyautogui.press == 'p':
        print("You pressed p")
        break
