import pyautogui
import keyboard 
import time
x = 0
lista = 100
pyautogui.alert("o código vai começar")
pyautogui.PAUSE = 0.3
pyautogui.moveTo(766, 888)     
pyautogui.click()
 
while True:
    pyautogui.moveTo(10, 187)
    pyautogui.click()
    time.sleep(1)
    pyautogui.moveTo(596, 158)
    pyautogui.click()
    pyautogui.moveTo(863, 885) #excell
    pyautogui.click()
    pyautogui.keyDown('ctrl')
    pyautogui.keyDown('c')
    pyautogui.keyUp('c')
    pyautogui.keyUp('ctrl')
    #pyautogui.hotkey('crtl', 'c')
    pyautogui.moveTo(766, 888)     
    pyautogui.click()
    pyautogui.moveTo(413, 217)
    pyautogui.click()
    pyautogui.keyDown('ctrl')
    pyautogui.keyDown('v')
    pyautogui.keyUp('v')
    pyautogui.keyUp('ctrl')
    #pyautogui.hotkey('crtl', 'v')
    pyautogui.moveTo(441, 149)
    pyautogui.click()
    pyautogui.moveTo(863, 885) #excell
    pyautogui.click()
    pyautogui.press('right')
    pyautogui.keyDown('ctrl')
    pyautogui.keyDown('c')
    pyautogui.keyUp('c')
    pyautogui.keyUp('ctrl')
    #pyautogui.hotkey('crtl', 'c')
    pyautogui.moveTo(766, 888)     
    pyautogui.click()
    pyautogui.moveTo(795, 274)
    pyautogui.click()
    pyautogui.keyDown('ctrl')
    pyautogui.keyDown('v')
    pyautogui.keyUp('v')
    pyautogui.keyUp('ctrl')
    #pyautogui.hotkey('crtl', 'v')
    pyautogui.moveTo(482, 237)
    pyautogui.click()
    pyautogui.moveTo(863, 885) #excell
    pyautogui.click()
    pyautogui.press('right')
    pyautogui.keyDown('ctrl')
    pyautogui.keyDown('c')
    pyautogui.keyUp('c')
    pyautogui.keyUp('ctrl')
    #pyautogui.hotkey('crtl', 'c')
    pyautogui.moveTo(766, 888)     
    pyautogui.click()
    pyautogui.keyDown('ctrl')
    pyautogui.keyDown('v')
    pyautogui.keyUp('v')
    pyautogui.keyUp('ctrl')
    #pyautogui.hotkey('crtl', 'v')
    pyautogui.moveTo(583, 272)     
    pyautogui.click()
    time.sleep(0.8)
    pyautogui.write('TO')
    pyautogui.press('enter')
    pyautogui.press('enter')
    pyautogui.press('tab')
    pyautogui.write('Palmas')
    pyautogui.press('enter')
    pyautogui.moveTo(748, 371)     
    pyautogui.click()
    pyautogui.press('enter')
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.write('.')
    pyautogui.moveTo(501, 411)     
    pyautogui.click()
    pyautogui.write('.')
    pyautogui.moveTo(516, 149)     
    pyautogui.click()
    pyautogui.moveTo(411, 204)     
    pyautogui.click()
    pyautogui.write('77000000')
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.write('.')
    pyautogui.press('tab')
    pyautogui.write('.')
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.write('.')
    pyautogui.moveTo(642, 325)     
    pyautogui.click()
    pyautogui.write('TO')
    pyautogui.press('enter')
    pyautogui.press('enter')
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.press('tab')
    time.sleep(0.8)
    pyautogui.write('63')
    pyautogui.press('tab')
    pyautogui.write('63')
    pyautogui.press('tab')
    pyautogui.write('63')
    pyautogui.press('tab')
    pyautogui.write('63')
    pyautogui.moveTo(1168, 759)     
    pyautogui.click()
    pyautogui.moveTo(1025, 760)     
    pyautogui.click()
    pyautogui.moveTo(863, 885) #excell
    pyautogui.click()
    pyautogui.press('up')
    pyautogui.press('left')
    pyautogui.press('left') 
    pyautogui.moveTo(766, 888)     
    pyautogui.click()


'''
    pyautogui.moveTo(538, 151)
    pyautogui.click()
    pyautogui.moveTo(12, 184)
    pyautogui.click()
    time.sleep(1)
    pyautogui.moveTo(596, 158)
    pyautogui.click()
    pyautogui.moveTo(863, 885)
    pyautogui.click()
    pyautogui.hotkey('crtl', 'c')
    pyautogui.moveTo(413, 217)
    pyautogui.click()
    pyautogui.hotkey('crtl', 'v')
    pyautogui.moveTo(441, 149)
    pyautogui.click()

    pyautogui.moveTo(795, 274)
    pyautogui.click()
'''